apiVersion: v1
kind: Service
metadata:
  name: package-service
spec:
  selector:
    app: package-service
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 31000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: package-service
spec:
  selector:
    matchLabels:
      app: package-service
  replicas: 1
  template:
    metadata:
      labels:
        app: package-service
    spec:
      containers:
        - name: server
          image: artemburd073/package-service
          ports:
            - name: http
              containerPort: 8080

---